# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@master
        
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/arm-deploy@v1
        with:
          # Provide the scope of the deployment. alid values are: 'resourcegroup', 'managementgroup', 'subscription'
          scope: resourcegroup
          # Provide the Id of the subscription which should be used.
          subscriptionId: '11321b33-1608-46d8-8a51-5d32cdd1b38a'
          # Provide the target region, only required for management Group or Subscription deployments.
          region: 'southeastasia'
          # Provide the name of a resource group.
          resourceGroupName: 'AzureChallengeGitHubActionsRG'
          # Specify the path or URL to the Azure Resource Manager template.
          template: ./template.json
         
